// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordsTrainer.Infrastructure.Data;

#nullable disable

namespace WordsTrainer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528110553_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordsTrainer.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NativeLanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LanguageLevelId");

                    b.HasIndex("NativeLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("LanguageLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeaningKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.ConceptExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ConceptId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ConceptExplanations");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.ConceptWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("ConceptId", "WordId")
                        .IsUnique();

                    b.ToTable("ConceptWords");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.LanguageLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreBefore")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreDelta")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("TrainingQuestionAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TranslationViewed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasNewConcept")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TrainingQuestionAttemptId");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("UserId", "AnsweredAtUtc");

                    b.HasIndex("UserId", "ConceptId", "AnsweredAtUtc");

                    b.ToTable("TrainingAnswers");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingQuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrectWordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionWordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId", "CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "ConceptId", "IsAnswered");

                    b.ToTable("TrainingQuestionAttempts");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingQuestionAttemptOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("TextSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("AttemptId", "WordId")
                        .IsUnique();

                    b.ToTable("TrainingQuestionAttemptOptions");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewConceptLimit")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.UserConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("integer");

                    b.Property<double>("EaseFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FirstShownAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCorrectAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastShownAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWrongAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LearnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextReviewAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<int>("TranslationViewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("UserId", "ConceptId")
                        .IsUnique();

                    b.ToTable("UserConcepts");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Text");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.AppUser", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.Language", "NativeLanguage")
                        .WithMany()
                        .HasForeignKey("NativeLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguageLevel");

                    b.Navigation("NativeLanguage");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Concept", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.ConceptExplanation", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.Concept", "Concept")
                        .WithMany("Explanations")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.ConceptWord", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.Concept", "Concept")
                        .WithMany("ConceptWords")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.Word", "Word")
                        .WithMany("ConceptWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingAnswer", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.TrainingQuestionAttempt", "TrainingQuestionAttempt")
                        .WithMany()
                        .HasForeignKey("TrainingQuestionAttemptId");

                    b.HasOne("WordsTrainer.Core.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Answers")
                        .HasForeignKey("TrainingSessionId");

                    b.Navigation("TrainingQuestionAttempt");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingQuestionAttempt", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Attempts")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingQuestionAttemptOption", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.TrainingQuestionAttempt", "Attempt")
                        .WithMany("Options")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingSession", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.AppUser", "User")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.UserConcept", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordsTrainer.Core.Entities.AppUser", "User")
                        .WithMany("UserConcepts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Word", b =>
                {
                    b.HasOne("WordsTrainer.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.AppUser", b =>
                {
                    b.Navigation("TrainingSessions");

                    b.Navigation("UserConcepts");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Concept", b =>
                {
                    b.Navigation("ConceptWords");

                    b.Navigation("Explanations");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingQuestionAttempt", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.TrainingSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("WordsTrainer.Core.Entities.Word", b =>
                {
                    b.Navigation("ConceptWords");
                });
#pragma warning restore 612, 618
        }
    }
}
