FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore WordsTrainer.Web/WordsTrainer.Web.csproj
RUN dotnet publish WordsTrainer.Web/WordsTrainer.Web.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["sh", "-c", "dotnet WordsTrainer.Web.dll --urls http://0.0.0.0:${PORT}"]
